
#  建库
create database: create database qcdb;
create user: create user 'qc'@'%' identified by 'qc123456';
grant privileges: grant all on qcdb.* to 'qc'@'%';
  
#  数据表
  /resources/sql
#  图片路径
  /resources/static/
